apiVersion: v1
kind: ConfigMap
metadata:
  name: synthetic-monitoring-config
  namespace: observability
data:
  config.yaml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          valid_status_codes: [200, 201, 202, 203, 204]
          method: GET
          preferred_ip_protocol: "ip4"
          follow_redirects: true
          fail_if_ssl: false
          fail_if_not_ssl: true
          tls_config:
            insecure_skip_verify: false
      http_post_2xx:
        prober: http
        timeout: 5s
        http:
          method: POST
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          valid_status_codes: [200, 201, 202, 203, 204]
          preferred_ip_protocol: "ip4"
          follow_redirects: true
          fail_if_ssl: false
          fail_if_not_ssl: true
          tls_config:
            insecure_skip_verify: false
      tcp_connect:
        prober: tcp
        timeout: 5s
        tcp:
          preferred_ip_protocol: "ip4"
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: api-health
  namespace: observability
  labels:
    app: apexagent
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter.observability:9115
  targets:
    staticConfig:
      static:
        - https://api.apexagent.example.com/health
      labels:
        service: api
        endpoint: health
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: frontend-health
  namespace: observability
  labels:
    app: apexagent
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter.observability:9115
  targets:
    staticConfig:
      static:
        - https://apexagent.example.com
      labels:
        service: frontend
        endpoint: root
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
      - name: blackbox-exporter
        image: prom/blackbox-exporter:latest
        args:
        - --config.file=/etc/blackbox_exporter/config.yaml
        ports:
        - containerPort: 9115
          name: http
        volumeMounts:
        - name: config
          mountPath: /etc/blackbox_exporter
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      volumes:
      - name: config
        configMap:
          name: synthetic-monitoring-config
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: observability
  labels:
    app: blackbox-exporter
spec:
  ports:
  - name: http
    port: 9115
    protocol: TCP
    targetPort: http
  selector:
    app: blackbox-exporter
  type: ClusterIP
