global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # ApexAgent application metrics
  - job_name: 'apexagent'
    static_configs:
      - targets: ['apexagent-app:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Custom business metrics
  - job_name: 'apexagent-business'
    static_configs:
      - targets: ['apexagent-app:5000']
    metrics_path: '/api/metrics/business'
    scrape_interval: 60s
    scrape_timeout: 15s

  # Security metrics
  - job_name: 'apexagent-security'
    static_configs:
      - targets: ['apexagent-app:5000']
    metrics_path: '/api/metrics/security'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Performance metrics
  - job_name: 'apexagent-performance'
    static_configs:
      - targets: ['apexagent-app:5000']
    metrics_path: '/api/metrics/performance'
    scrape_interval: 30s
    scrape_timeout: 10s

