apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-component-monitor
  namespace: observability
  labels:
    monitoring: istio-components
spec:
  selector:
    matchLabels:
      istio: pilot
  namespaceSelector:
    matchNames:
    - istio-system
  endpoints:
  - port: http-monitoring
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-stats-monitor
  namespace: observability
  labels:
    monitoring: istio-proxies
spec:
  selector:
    matchExpressions:
    - {key: istio-prometheus-ignore, operator: DoesNotExist}
  namespaceSelector:
    any: true
  endpoints:
  - path: /stats/prometheus
    targetPort: 15090
    interval: 15s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_container_port_name]
      action: keep
      regex: '.*-envoy-prom'
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: prometheus-external
  namespace: istio-system
spec:
  hosts:
  - prometheus.observability.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
  - number: 9090
    name: prometheus
    protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: grafana-external
  namespace: istio-system
spec:
  hosts:
  - grafana.observability.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
  - number: 3000
    name: grafana
    protocol: HTTP
  resolution: DNS
